[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "unsupervised_learning"
version = "0.1.0"
readme = "README.md"
description = "Project that uses MOMENT pre-trained with 3W dataset for anomaly detection in unlabeled data"
requires-python = ">=3.10"

dependencies = [
    # MOMENT v0.1.5
    # v0.1.5 is not published on PyPI; pinned to commit 38f7310
    "momentfm @ git+https://github.com/moment-timeseries-foundation-model/moment.git@38f7310",

    "threewtoolkit==3.2.1",
]

[dependency-groups]
dev = [
    "ipykernel",
    "ipywidgets",
    "jupyter-client",
    "jupyter-core",
    "jupyterlab",
]
